apiVersion: 1
datasources:
  - name: Neon PostgreSQL
    type: postgres
    url: ${DATABASE_HOST}:5432
    database: neondb
    user: ${DATABASE_USER}
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1500
